import type { FurnitureCategory, FurnitureCatalogItem } from '@/models'

export const CATEGORY_LABELS: Record<FurnitureCategory, string> = {
  seating: 'Seating',
  tables: 'Tables',
  storage: 'Storage',
  beds: 'Beds',
  lighting: 'Lighting',
  decor: 'Decor',
  appliances: 'Appliances',
  bathroom: 'Bathroom',
  outdoor: 'Outdoor',
}

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
  // Seating
  {
    id: 'sofa-3-seat',
    name: '3-Seat Sofa',
    category: 'seating',
    modelPath: '/models/sofa-3-seat.glb',
    thumbnail: '/thumbnails/sofa-3-seat.png',
    defaultDimensions: { width: 220, depth: 90, height: 85 },
    canResize: true,
    resizeConstraints: { minWidth: 180, maxWidth: 280 },
    defaultMaterial: { materialId: 'fabric-gray' },
    customizableParts: [],
  },
  {
    id: 'sofa-2-seat',
    name: '2-Seat Sofa',
    category: 'seating',
    modelPath: '/models/sofa-2-seat.glb',
    thumbnail: '/thumbnails/sofa-2-seat.png',
    defaultDimensions: { width: 160, depth: 90, height: 85 },
    canResize: true,
    resizeConstraints: { minWidth: 140, maxWidth: 200 },
    defaultMaterial: { materialId: 'fabric-gray' },
    customizableParts: [],
  },
  {
    id: 'armchair',
    name: 'Armchair',
    category: 'seating',
    modelPath: '/models/armchair.glb',
    thumbnail: '/thumbnails/armchair.png',
    defaultDimensions: { width: 85, depth: 90, height: 95 },
    canResize: false,
    defaultMaterial: { materialId: 'fabric-beige' },
    customizableParts: [],
  },
  {
    id: 'dining-chair',
    name: 'Dining Chair',
    category: 'seating',
    modelPath: '/models/dining-chair.glb',
    thumbnail: '/thumbnails/dining-chair.png',
    defaultDimensions: { width: 45, depth: 50, height: 90 },
    canResize: false,
    defaultMaterial: { materialId: 'wood-oak' },
    customizableParts: [],
  },
  {
    id: 'office-chair',
    name: 'Office Chair',
    category: 'seating',
    modelPath: '/models/office-chair.glb',
    thumbnail: '/thumbnails/office-chair.png',
    defaultDimensions: { width: 65, depth: 65, height: 115 },
    canResize: false,
    defaultMaterial: { materialId: 'fabric-black' },
    customizableParts: [],
  },

  // Tables
  {
    id: 'dining-table-rect',
    name: 'Dining Table',
    category: 'tables',
    modelPath: '/models/dining-table-rect.glb',
    thumbnail: '/thumbnails/dining-table-rect.png',
    defaultDimensions: { width: 180, depth: 90, height: 75 },
    canResize: true,
    resizeConstraints: { minWidth: 120, maxWidth: 300, minDepth: 80, maxDepth: 120 },
    defaultMaterial: { materialId: 'wood-walnut' },
    customizableParts: [],
  },
  {
    id: 'coffee-table',
    name: 'Coffee Table',
    category: 'tables',
    modelPath: '/models/coffee-table.glb',
    thumbnail: '/thumbnails/coffee-table.png',
    defaultDimensions: { width: 120, depth: 60, height: 45 },
    canResize: true,
    defaultMaterial: { materialId: 'wood-oak' },
    customizableParts: [],
  },
  {
    id: 'side-table',
    name: 'Side Table',
    category: 'tables',
    modelPath: '/models/side-table.glb',
    thumbnail: '/thumbnails/side-table.png',
    defaultDimensions: { width: 50, depth: 50, height: 55 },
    canResize: false,
    defaultMaterial: { materialId: 'wood-oak' },
    customizableParts: [],
  },
  {
    id: 'desk',
    name: 'Office Desk',
    category: 'tables',
    modelPath: '/models/desk.glb',
    thumbnail: '/thumbnails/desk.png',
    defaultDimensions: { width: 140, depth: 70, height: 75 },
    canResize: true,
    resizeConstraints: { minWidth: 100, maxWidth: 200 },
    defaultMaterial: { materialId: 'wood-white' },
    customizableParts: [],
  },

  // Beds
  {
    id: 'bed-king',
    name: 'King Bed',
    category: 'beds',
    modelPath: '/models/bed-king.glb',
    thumbnail: '/thumbnails/bed-king.png',
    defaultDimensions: { width: 193, depth: 203, height: 100 },
    canResize: false,
    defaultMaterial: { materialId: 'fabric-white' },
    customizableParts: [],
  },
  {
    id: 'bed-queen',
    name: 'Queen Bed',
    category: 'beds',
    modelPath: '/models/bed-queen.glb',
    thumbnail: '/thumbnails/bed-queen.png',
    defaultDimensions: { width: 153, depth: 203, height: 100 },
    canResize: false,
    defaultMaterial: { materialId: 'fabric-white' },
    customizableParts: [],
  },
  {
    id: 'bed-single',
    name: 'Single Bed',
    category: 'beds',
    modelPath: '/models/bed-single.glb',
    thumbnail: '/thumbnails/bed-single.png',
    defaultDimensions: { width: 90, depth: 190, height: 100 },
    canResize: false,
    defaultMaterial: { materialId: 'fabric-white' },
    customizableParts: [],
  },
  {
    id: 'nightstand',
    name: 'Nightstand',
    category: 'beds',
    modelPath: '/models/nightstand.glb',
    thumbnail: '/thumbnails/nightstand.png',
    defaultDimensions: { width: 50, depth: 40, height: 55 },
    canResize: false,
    defaultMaterial: { materialId: 'wood-walnut' },
    customizableParts: [],
  },

  // Storage
  {
    id: 'bookshelf',
    name: 'Bookshelf',
    category: 'storage',
    modelPath: '/models/bookshelf.glb',
    thumbnail: '/thumbnails/bookshelf.png',
    defaultDimensions: { width: 80, depth: 35, height: 200 },
    canResize: true,
    resizeConstraints: { minWidth: 60, maxWidth: 120 },
    defaultMaterial: { materialId: 'wood-oak' },
    customizableParts: [],
  },
  {
    id: 'wardrobe',
    name: 'Wardrobe',
    category: 'storage',
    modelPath: '/models/wardrobe.glb',
    thumbnail: '/thumbnails/wardrobe.png',
    defaultDimensions: { width: 150, depth: 60, height: 220 },
    canResize: true,
    resizeConstraints: { minWidth: 100, maxWidth: 250 },
    defaultMaterial: { materialId: 'wood-white' },
    customizableParts: [],
  },
  {
    id: 'dresser',
    name: 'Dresser',
    category: 'storage',
    modelPath: '/models/dresser.glb',
    thumbnail: '/thumbnails/dresser.png',
    defaultDimensions: { width: 120, depth: 50, height: 80 },
    canResize: false,
    defaultMaterial: { materialId: 'wood-walnut' },
    customizableParts: [],
  },
  {
    id: 'tv-stand',
    name: 'TV Stand',
    category: 'storage',
    modelPath: '/models/tv-stand.glb',
    thumbnail: '/thumbnails/tv-stand.png',
    defaultDimensions: { width: 150, depth: 45, height: 50 },
    canResize: true,
    defaultMaterial: { materialId: 'wood-oak' },
    customizableParts: [],
  },

  // Lighting
  {
    id: 'floor-lamp',
    name: 'Floor Lamp',
    category: 'lighting',
    modelPath: '/models/floor-lamp.glb',
    thumbnail: '/thumbnails/floor-lamp.png',
    defaultDimensions: { width: 40, depth: 40, height: 160 },
    canResize: false,
    defaultMaterial: { materialId: 'metal-black' },
    customizableParts: [],
  },
  {
    id: 'table-lamp',
    name: 'Table Lamp',
    category: 'lighting',
    modelPath: '/models/table-lamp.glb',
    thumbnail: '/thumbnails/table-lamp.png',
    defaultDimensions: { width: 30, depth: 30, height: 50 },
    canResize: false,
    defaultMaterial: { materialId: 'ceramic-white' },
    customizableParts: [],
  },
  {
    id: 'pendant-light',
    name: 'Pendant Light',
    category: 'lighting',
    modelPath: '/models/pendant-light.glb',
    thumbnail: '/thumbnails/pendant-light.png',
    defaultDimensions: { width: 40, depth: 40, height: 30 },
    canResize: false,
    defaultMaterial: { materialId: 'metal-brass' },
    customizableParts: [],
  },

  // Decor
  {
    id: 'plant-large',
    name: 'Large Plant',
    category: 'decor',
    modelPath: '/models/plant-large.glb',
    thumbnail: '/thumbnails/plant-large.png',
    defaultDimensions: { width: 50, depth: 50, height: 150 },
    canResize: false,
    defaultMaterial: { materialId: 'plant-green' },
    customizableParts: [],
  },
  {
    id: 'plant-small',
    name: 'Small Plant',
    category: 'decor',
    modelPath: '/models/plant-small.glb',
    thumbnail: '/thumbnails/plant-small.png',
    defaultDimensions: { width: 25, depth: 25, height: 40 },
    canResize: false,
    defaultMaterial: { materialId: 'plant-green' },
    customizableParts: [],
  },
  {
    id: 'rug-rect',
    name: 'Area Rug',
    category: 'decor',
    modelPath: '/models/rug-rect.glb',
    thumbnail: '/thumbnails/rug-rect.png',
    defaultDimensions: { width: 200, depth: 140, height: 2 },
    canResize: true,
    defaultMaterial: { materialId: 'fabric-beige' },
    customizableParts: [],
  },
  {
    id: 'mirror',
    name: 'Wall Mirror',
    category: 'decor',
    modelPath: '/models/mirror.glb',
    thumbnail: '/thumbnails/mirror.png',
    defaultDimensions: { width: 60, depth: 5, height: 120 },
    canResize: false,
    defaultMaterial: { materialId: 'metal-gold' },
    customizableParts: [],
  },

  // Appliances
  {
    id: 'refrigerator',
    name: 'Refrigerator',
    category: 'appliances',
    modelPath: '/models/refrigerator.glb',
    thumbnail: '/thumbnails/refrigerator.png',
    defaultDimensions: { width: 90, depth: 70, height: 180 },
    canResize: false,
    defaultMaterial: { materialId: 'metal-stainless' },
    customizableParts: [],
  },
  {
    id: 'stove',
    name: 'Stove',
    category: 'appliances',
    modelPath: '/models/stove.glb',
    thumbnail: '/thumbnails/stove.png',
    defaultDimensions: { width: 60, depth: 60, height: 90 },
    canResize: false,
    defaultMaterial: { materialId: 'metal-stainless' },
    customizableParts: [],
  },
  {
    id: 'dishwasher',
    name: 'Dishwasher',
    category: 'appliances',
    modelPath: '/models/dishwasher.glb',
    thumbnail: '/thumbnails/dishwasher.png',
    defaultDimensions: { width: 60, depth: 60, height: 85 },
    canResize: false,
    defaultMaterial: { materialId: 'metal-stainless' },
    customizableParts: [],
  },
  {
    id: 'washer',
    name: 'Washing Machine',
    category: 'appliances',
    modelPath: '/models/washer.glb',
    thumbnail: '/thumbnails/washer.png',
    defaultDimensions: { width: 60, depth: 60, height: 85 },
    canResize: false,
    defaultMaterial: { materialId: 'metal-white' },
    customizableParts: [],
  },

  // Bathroom
  {
    id: 'toilet',
    name: 'Toilet',
    category: 'bathroom',
    modelPath: '/models/toilet.glb',
    thumbnail: '/thumbnails/toilet.png',
    defaultDimensions: { width: 40, depth: 70, height: 80 },
    canResize: false,
    defaultMaterial: { materialId: 'ceramic-white' },
    customizableParts: [],
  },
  {
    id: 'sink-bathroom',
    name: 'Bathroom Sink',
    category: 'bathroom',
    modelPath: '/models/sink-bathroom.glb',
    thumbnail: '/thumbnails/sink-bathroom.png',
    defaultDimensions: { width: 60, depth: 50, height: 85 },
    canResize: false,
    defaultMaterial: { materialId: 'ceramic-white' },
    customizableParts: [],
  },
  {
    id: 'bathtub',
    name: 'Bathtub',
    category: 'bathroom',
    modelPath: '/models/bathtub.glb',
    thumbnail: '/thumbnails/bathtub.png',
    defaultDimensions: { width: 170, depth: 75, height: 60 },
    canResize: false,
    defaultMaterial: { materialId: 'ceramic-white' },
    customizableParts: [],
  },
  {
    id: 'shower',
    name: 'Shower',
    category: 'bathroom',
    modelPath: '/models/shower.glb',
    thumbnail: '/thumbnails/shower.png',
    defaultDimensions: { width: 90, depth: 90, height: 210 },
    canResize: true,
    defaultMaterial: { materialId: 'glass-clear' },
    customizableParts: [],
  },

  // Outdoor
  {
    id: 'outdoor-chair',
    name: 'Outdoor Chair',
    category: 'outdoor',
    modelPath: '/models/outdoor-chair.glb',
    thumbnail: '/thumbnails/outdoor-chair.png',
    defaultDimensions: { width: 60, depth: 65, height: 85 },
    canResize: false,
    defaultMaterial: { materialId: 'wood-teak' },
    customizableParts: [],
  },
  {
    id: 'outdoor-table',
    name: 'Outdoor Table',
    category: 'outdoor',
    modelPath: '/models/outdoor-table.glb',
    thumbnail: '/thumbnails/outdoor-table.png',
    defaultDimensions: { width: 120, depth: 80, height: 75 },
    canResize: true,
    defaultMaterial: { materialId: 'wood-teak' },
    customizableParts: [],
  },
  {
    id: 'planter',
    name: 'Planter',
    category: 'outdoor',
    modelPath: '/models/planter.glb',
    thumbnail: '/thumbnails/planter.png',
    defaultDimensions: { width: 50, depth: 50, height: 50 },
    canResize: true,
    defaultMaterial: { materialId: 'ceramic-terracotta' },
    customizableParts: [],
  },
]

export function getFurnitureByCategory(category: FurnitureCategory): FurnitureCatalogItem[] {
  return FURNITURE_CATALOG.filter((item) => item.category === category)
}

export function getFurnitureById(id: string): FurnitureCatalogItem | undefined {
  return FURNITURE_CATALOG.find((item) => item.id === id)
}

export function getAllFurniture(): FurnitureCatalogItem[] {
  return FURNITURE_CATALOG
}
